apiVersion: v1
kind: Pod
metadata:
  name: monitor-all-in-one
  # namespace: hitwhvg-monitoring
  labels:
    app: monitor
spec:
  containers:
  - name: prometheus-with-ne
    image: hitwhvg/prom-ne:arhshrn
    imagePullPolicy: Never
    ports:
    - name: prom-port
      containerPort: 9090
      hostPort: 9090
      protocol: TCP
  - name: grafana
    image: hitwhvg/grafana:v5.4.0
    imagePullPolicy: Never
    ports:
    - name: grafana-port
      containerPort: 3000
      hostPort: 3000
      protocol: TCP