apiVersion: v1
kind: Service
metadata:
  name: monitor
  labels:
    app: monitor
spec:
  type: NodePort
  selector:
    app: monitor
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 8400
  - name: grafana
    port: 3000
    targetPort: 3000
    nodePort: 8401
  - name: prom
    port: 9090
    targetPort: 9090
    nodePort: 8402
  - name: ne
    port: 9100
    targetPort: 9100
    nodePort: 8403
# ---
# apiVersion: extensions/v1beta1
# kind: DaemonSet
# metadata:
#   name: monitor
#   labels:
#     addonmanager.kubernetes.io/mode: Reconcile
# spec:
#   template:
#     metadata:
#       labels:
#         app: monitor
#     spec:
#       containers:
#       - name: grafana
#         image: hitwhvg/grafana:v5.4.0
#         ports:
#         - containerPort: 3000
#         env:
#         - name: GF_SECURITY_ADMIN_USER
#           value: admin
#         - name: GF_SECURITY_ADMIN_PASSWORD
#           value: admin
#       - name: promne
#         image: hitwhvg/prom-ne:arhshrn
#         ports:
#         - containerPort: 9090