apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 80
  selector:
    app: grafana
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: grafana
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: my-grafana
        image: hitwhvg/grafana:v5.4.0
        ports:
        - containerPort: 3000